apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      nodePort: 30083 # exposing to local, to access this service
      targetPort: 8083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: proj2_order-service
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: PRODUCT_SERVICE_URL
              value: product-service
            - name: ACCOUNT_SERVICE_URL
              value: account-service
            - name: BANK_SERVICE_URL
              value: bank-service
            - name: CREDIT_SERVICE_URL
              value: credit-service
            - name: PAYPAL_SERVICE_URL
              value: paypal-service
            - name: STOCK_SERVICE_URL
              value: stock-service
            - name: SHIPPING_SERVICE_URL
              value: shipping-service
            - name: TRANSACTION_SERVICE_URL
              value: transaction-service
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: order_mysqlURL

            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: order_dbName
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret-key
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
          imagePullPolicy: Never