server:
  port: 8083


spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:order-db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Root#1234}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:swa-proj1-jwt-secret}
      expire-seconds: 86400
  url:
    product-service: ${PRODUCT_SERVICE_URL:localhost:8081}
    account-service: ${ACCOUNT_SERVICE_URL:localhost:8082}
    bank-service: ${BANK_SERVICE_URL:localhost:8084}
    credit-service: ${CREDIT_SERVICE_URL:localhost:8085}
    paypal-service: ${PAYPAL_SERVICE_URL:localhost:8086}
    stock-service: ${STOCK_SERVICE_URL:localhost:8087}
    shipping-service: ${SHIPPING_SERVICE_URL:localhost:8088}
    transaction-service: ${TRANSACTION_SERVICE_URL:localhost:8089}




