apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  jwt-secret-key: swa-proj1-jwt-secret
  product-feign-key: secret-product-feign-key
  payment-key: secret-payment-feign-key